/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:599539:
  send = true;
} //_CODE_:button1:599539:

public void newLocationSlide(GCustomSlider source, GEvent event) { //_CODE_:newLocation:315396:
  println("custom_slider1 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:newLocation:315396:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 56, 38, 80, 30);
  button1.setText("penis");
  button1.addEventHandler(this, "button1_click1");
  newLocation = new GCustomSlider(this, 47, 90, 100, 40, "grey_blue");
  newLocation.setShowValue(true);
  newLocation.setShowLimits(true);
  newLocation.setLimits(0.5, 0.0, 100.0);
  newLocation.setShowTicks(true);
  newLocation.setNumberFormat(G4P.DECIMAL, 2);
  newLocation.setOpaque(false);
  newLocation.addEventHandler(this, "newLocationSlide");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GCustomSlider newLocation; 
