/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void camButtonClicked(GButton source, GEvent event) { //_CODE_:camButton:599539:
  send = true;
} //_CODE_:camButton:599539:

public void confirmButtonClicked(GButton source, GEvent event) { //_CODE_:confirmButton:217314:
  sendToHardware = true;
  if (sendToHardware == true) {
    println(xLocation);
    sendToHardware = false;
  }
} //_CODE_:confirmButton:217314:

public void LocSliMoved(GSlider source, GEvent event) { //_CODE_:LocationSlider:479904:
  xLocation = LocationSlider.getValueI();
} //_CODE_:LocationSlider:479904:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  camButton = new GButton(this, 55, 70, 80, 30);
  camButton.setText("Take Snapshot");
  camButton.addEventHandler(this, "camButtonClicked");
  confirmButton = new GButton(this, 55, 200, 80, 30);
  confirmButton.setText("Confirm Move");
  confirmButton.addEventHandler(this, "confirmButtonClicked");
  label1 = new GLabel(this, 45, 27, 100, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("StrongArm command center");
  label1.setOpaque(false);
  LocationSlider = new GSlider(this, 29, 130, 147, 40, 10.0);
  LocationSlider.setShowValue(true);
  LocationSlider.setShowLimits(true);
  LocationSlider.setLimits(0.0, 0.0, 2000.0);
  LocationSlider.setShowTicks(true);
  LocationSlider.setNumberFormat(G4P.DECIMAL, 2);
  LocationSlider.setOpaque(false);
  LocationSlider.addEventHandler(this, "LocSliMoved");
}

// Variable declarations 
// autogenerated do not edit
GButton camButton; 
GButton confirmButton; 
GLabel label1; 
GSlider LocationSlider; 
